#pragma once

#include <QMainWindow>
#include <array>
#include "../models/Schedule.h"

/*
 * Forward declaration of UI class generated by Qt Designer.
 */
QT_BEGIN_NAMESPACE
namespace Ui {
class ScheduleBuilderWindow;
}
QT_END_NAMESPACE

/*
 * Forward declaration of SimulationWindow to avoid circular dependency.
 */
class SimulationWindow;

/*
 * ScheduleBuilderWindow
 *
 * Main application window responsible for:
 *  - Creating and managing a weekly schedule
 *  - Handling all user interactions (buttons, table selection, dropdowns)
 *  - Displaying schedule data in a 15-minute resolution table
 *  - Launching the simulation based on user-defined activities
 *
 * Structure:
 *  - Each day has its own Schedule object
 *  - The UI table maps directly to these schedules
 *  - Time is represented in hours but visualized in 15-minute intervals
 */
class ScheduleBuilderWindow : public QMainWindow
{
    Q_OBJECT

public:
    /*
     * Constructor
     * Initializes UI and prepares application state.
     */
    explicit ScheduleBuilderWindow(QWidget *parent = nullptr);

    /*
     * Destructor
     */
    ~ScheduleBuilderWindow();

private slots:

    /*
     * Triggered when user clicks "Add Activity"
     * Creates a new activity and inserts it into the current day's schedule.
     */
    void onAddActivityClicked();

    /*
     * Triggered when user clicks "Start Simulation"
     * Combines all daily schedules and launches simulation window.
     */
    void onStartSimulationClicked();

    /*
     * Triggered when user clicks "Delete Activity"
     * Removes the activity corresponding to the selected table cell.
     */
    void onDeleteActivityClicked();

    /*
     * Triggered when the selected day changes in the dropdown.
     * Updates currentDay and refreshes UI state.
     */
    void onDayChanged(int dayIndex);

private:

    /*
     * Pointer to UI elements (auto-generated from .ui file)
     */
    Ui::ScheduleBuilderWindow *ui;

    /*
     * Stores one Schedule object per day (Monday–Sunday).
     * Index mapping:
     *  0 = Monday, 1 = Tuesday, ..., 6 = Sunday
     */
    std::array<Schedule, 7> weekSchedules;

    /*
     * Currently selected day index.
     * Used to determine which schedule to modify.
     */
    int currentDay = 0;

    /*
     * Pointer to simulation window instance.
     * Created when simulation starts.
     */
    SimulationWindow *simulationWindow;

    /*
     * Updates remaining available hours for the current day.
     */
    void updateRemainingHours();

    /*
     * Triggered when user selects cells in the schedule table.
     *
     * Responsibilities:
     *  - Convert selected rows into start/end time
     *  - Update time dropdowns
     *  - Detect selected day (column)
     */
    void onTableSelectionChanged();

    /*
     * Rebuilds the UI table for a specific day.
     *
     * Clears the column and re-renders all activities
     * belonging to that day.
     */
    void rebuildTableForDay(int day);

    /*
     * Initializes UI components and table structure.
     */
    void setupUiData();

    void loadHardModeSchedule();

    /*
     * Converts string from UI into ActivityType enum.
     */
    ActivityType stringToActivityType(const QString& typeText) const;

    /*
     * Converts ActivityType enum into display string.
     */
    QString activityTypeToString(ActivityType type) const;
};