#pragma once

#include <QWidget>
#include <QLabel>
#include <QMainWindow>
#include "../models/Schedule.h"
#include "../models/Stats.h"
#include "../engine/SimulationEngine.h"

/*
 * Forward declaration of UI class generated by Qt Designer.
 */
QT_BEGIN_NAMESPACE
namespace Ui {
class SimulationWindow;
}
QT_END_NAMESPACE

/*
 * SimulationWindow
 *
 * This class represents the simulation interface of the application.
 *
 * Responsibilities:
 *  - Executes a simulation based on the user's schedule
 *  - Iterates through activities sequentially
 *  - Updates and displays user stats (health, energy, etc.)
 *  - Handles decision events and random events
 *  - Produces a final evaluation of the schedule
 *
 * Simulation Model:
 *  - Each activity affects the user's stats
 *  - Decision events allow user interaction (choices)
 *  - Random events introduce unpredictability
 *  - Simulation ends when all activities are processed or stats drop too low
 */
class SimulationWindow : public QMainWindow
{
    Q_OBJECT

public:

    /*
     * Constructor
     *
     * Takes a complete Schedule object and initializes
     * the simulation starting from the first activity.
     */
    explicit SimulationWindow(const Schedule& schedule, QWidget *parent = nullptr);

    /*
     * Destructor
     */
    ~SimulationWindow();

private slots:

    /*
     * Advances the simulation to the next activity.
     *
     * Handles:
     *  - Applying activity effects
     *  - Triggering decision or random events
     *  - Checking survival conditions
     */
    void onNextActivityClicked();

    /*
     * Triggered when user clicks restart button.
     * Closes the simulation window.
     */
    void onRestartClicked();

private:

    /*
     * Pointer to UI components.
     */
    Ui::SimulationWindow *ui;

    /*
     * The full schedule being simulated.
     */
    Schedule schedule;

    /*
     * Current user stats (health, energy, stress, etc.).
     */
    Stats stats;

    /*
     * Core engine that processes activity effects and events.
     */
    SimulationEngine engine;

    /*
     * Index of the current activity being processed.
     */
    int currentIndex;

    /*
     * Updates UI progress bars to reflect current stats.
     */
    void updateStatsDisplay();

    /*
     * Updates the label showing the current activity.
     */
    void updateActivityDisplay();

    /*
     * Ends the simulation and displays final results.
     *
     * Includes:
     *  - Final stats
     *  - Performance rating
     *  - Suggestions for improvement
     */
    void finishSimulation(const QString& message);
};